### ISSUE TITLE
Cannot download pretrained model

### ISSUE THREAD

**Issue by joker452** [tomfalainen/neural-ctrlf#1]
I tried to use the script you provided (download_models.sh) to download the pretrained model, but some errors occurred. Can you give me some hints? Thanks.
Traceback (most recent call last):
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _                   new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79,                    in create_connection
    raise err
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69,                    in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600,                    in urlopen
    chunked=chunked)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343,                    in _make_request
    self._validate_conn(conn)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849,                    in _validate_conn
    conn.connect()
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 314, in c                   onnect
    conn = self._new_conn()
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _                   new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x                   7fdb40091f28>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deng/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 445, in se                   nd
    timeout=timeout
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638,                    in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/deng/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in i                   ncrement
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max re                   tries exceeded with url: /uc?export=download&id=0B3A3gL1SjnBMR1BxMktCRlJHMk0 (Caused by NewConn                   ectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdb40091f28>: Failed to e                   stablish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/download_utilities.py", line 36, in <module>
    download_file_from_google_drive(file_id, destination)
  File "scripts/download_utilities.py", line 9, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 525, in ge                   t
    return self.request('GET', url, **kwargs)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 512, in re                   quest
    resp = self.send(prep, **send_kwargs)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 622, in se                   nd
    r = adapter.send(request, **kwargs)
  File "/home/deng/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 513, in se                   nd
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max                    retries exceeded with url: /uc?export=download&id=0B3A3gL1SjnBMR1BxMktCRlJHMk0 (Caused by NewC                   onnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdb40091f28>: Failed t                   o establish a new connection: [Errno 101] Network is unreachable'))

**Comment by tomfalainen** [comment]
I forgot to mention in the installation instructions, but the python code is in version 2.7, which might be the source of your errors. I can run the script using python 2.7.14 and the anaconda distribution.

**Comment by joker452** [comment]
Thanks for your timely reply.  I found the error was actually caused by the Great Fire Wall of China which forbids me visiting google drive. I solved it by using a VPN. Thanks again.
